[workspace]
resolver = "2"
members = ["bin/*", "crates/*", "guests", "testing/ef-tests"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3

# RISC Zero
[workspace.dependencies.bonsai-sdk]
# git = "https://github.com/risc0/risc0"
# rev = "8801e2e3cd030acea2f03f01bd91f37e47e79e23"
path = "../../infra/risc0/bonsai/sdk"
features = ["non_blocking"]

[workspace.dependencies.risc0-build]
# git = "https://github.com/risc0/risc0"
# rev = "8801e2e3cd030acea2f03f01bd91f37e47e79e23"
path = "../../infra/risc0/risc0/build"
features = ["unstable"]

[workspace.dependencies.risc0-zkvm]
# git = "https://github.com/risc0/risc0"
# rev = "8801e2e3cd030acea2f03f01bd91f37e47e79e23"
path = "../../infra/risc0/risc0/zkvm"
default-features = false
features = ["bonsai"]

# External
[workspace.dependencies]
# Alloy
alloy = { version = "0.4.2", features = ["full"] }
alloy-chains = "0.1.38"
alloy-consensus = "0.4.2"
alloy-genesis = "0.4.2"
alloy-primitives = { version = "0.8.8", default-features = false, features = ["k256"] }
alloy-rlp = "0.3.8"
op-alloy-consensus = "0.4.0"
op-alloy-network = "0.4.0"
op-alloy-rpc-types = "0.4.0"

# Reth
reth-chainspec = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false, features = [
    "std",
] }
reth-consensus = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd" }
reth-ethereum-consensus = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd" }
reth-evm = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false, features = [
    "std",
] }
reth-evm-ethereum = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false, features = [
    "std",
] }
reth-optimism-chainspec = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false, features = [
    "std",
] }
reth-optimism-consensus = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd" }
reth-optimism-evm = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false }
reth-optimism-forks = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false }
reth-primitives = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false, features = [
    "std",
    "alloy-compat",
] }
reth-revm = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false, features = [
    "std",
] }
reth-storage-errors = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false, features = [
    "std",
] }

# Zeth
zeth = { path = "crates/zeth" }
zeth-core = { path = "crates/core" }
zeth-core-ethereum = { path = "crates/core-ethereum" }
zeth-core-optimism = { path = "crates/core-optimism" }
zeth-guests = { path = "guests" }
zeth-preflight = { path = "crates/preflight" }
zeth-preflight-ethereum = { path = "crates/preflight-ethereum" }
zeth-preflight-optimism = { path = "crates/preflight-optimism" }

# Others
anyhow = "1.0.89"
async-trait = "0.1.83"
bincode = "1.3.3"
bytemuck = "1.19.0"
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.11.5"
k256 = { version = "0.13.3", features = ["serde", "pem"] }
log = "0.4.22"
flate2 = "1.0.34"
once_cell = "1.20.2"
pot = "3.0.1"
rkyv = "0.8.9"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", features = ["alloc"] }
serde_with = "3.11.0"
thiserror = "1.0.64"
tiny-keccak = "2.0.2"
tokio = { version = "1.41.0", features = ["full"] }
tracing = { version = "0.1.40", features = ["log"] }
